package castlepanic.game.monster;

public enum MonsterAbility {
    ALL_PLAYERS_DISCARD_ONE_CARD,
    BASILISK,
    CHIMERA,
    CLIMB_WALLS,
    CONJURER,
    DOPPELGANGER,
    DRAGON,
    DRAW_3_MONSTER_TOKENS,
    DRAW_4_MONSTER_TOKENS,
    FIRE_STARTER,            // Starts a fire when it hits a wall or tower
    FLYING,
    GIANT_BOULDER,
    GOBLIN_KING,
    HEALER,
    HYDRA,
    IMP_PER_TOWER,
    MONSTERS_MOVE_1_BLUE,
    MONSTERS_MOVE_1_GREEN,
    MONSTERS_MOVE_1_RED,
    MONSTERS_MOVE_CLOCKWISE,
    MONSTERS_MOVE_COUNTER_CLOCKWISE,
    MOVE_2_SPACES,
    NECROMANCER,
    ORC_WARLORD,
    PLAGUE_ARCHERS,
    PLAGUE_KNIGHTS,
    PLAGUE_SWORDSMEN,
    TREBUCHET,
    TROLL_MAGE,
    WARLOCK
}
