package castlepanic.game;

public enum PhaseStep {
    START_PHASE,
    END_PHASE,

    PLAY_DRAW_UP,
    PLAY_DISCARD_AND_DRAW_1,
    PLAY_DISCARD_AND_DRAW_2,
    PLAY_CARDS,
    PLAY_MOVE_MONSTERS,
    PLAY_DAMAGE_BURNING_MONSTERS,
    PLAY_REMOVE_DESTROYED_MONSTERS,
    PLAY_DRAW_NEW_MONSTERS
}
